/**
 * Enhanced Demo data for Labour Mobility platform
 * Used when VITE_DEMO_MODE=true
 */

export const demoUsers = [
  {
    id: 1,
    email: 'admin@labormobility.com',
    password: 'admin123',
    firstName: 'Alexandra',
    lastName: 'Rodriguez',
    role: 'admin',
    isActive: true,
    avatar:
      'https://images.unsplash.com/photo-1494790108755-2616b612b1e5?w=150&h=150&fit=crop&crop=face',
    phone: '+1-555-0101',
    department: 'Administration',
    joinedDate: '2023-01-01T00:00:00Z',
    lastLogin: '2024-01-21T08:30:00Z',
    permissions: ['all'],
  },
  {
    id: 2,
    email: 'trainer@labormobility.com',
    password: 'trainer123',
    firstName: 'Michael',
    lastName: 'Chen',
    role: 'trainer',
    isActive: true,
    avatar:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    phone: '+1-555-0102',
    department: 'Training',
    specialization: 'Construction & Safety',
    joinedDate: '2023-02-15T00:00:00Z',
    lastLogin: '2024-01-21T09:15:00Z',
    certifications: ['OSHA Certified', 'First Aid Instructor'],
    permissions: ['training', 'assessments'],
  },
  {
    id: 3,
    email: 'candidate@labormobility.com',
    password: 'candidate123',
    firstName: 'Sarah',
    lastName: 'Johnson',
    role: 'candidate',
    isActive: true,
    avatar:
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    phone: '+1-555-0103',
    nationality: 'American',
    dateOfBirth: '1995-03-15',
    joinedDate: '2024-01-15T00:00:00Z',
    lastLogin: '2024-01-21T07:45:00Z',
    currentProgram: 'Healthcare Assistant Training',
  },
  {
    id: 4,
    email: 'recruiter@labormobility.com',
    password: 'recruiter123',
    firstName: 'David',
    lastName: 'Thompson',
    role: 'recruiter',
    isActive: true,
    avatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    phone: '+1-555-0104',
    department: 'Recruitment',
    territory: 'North America',
    joinedDate: '2023-06-01T00:00:00Z',
    lastLogin: '2024-01-21T10:20:00Z',
    permissions: ['candidates', 'placements'],
  },
  {
    id: 5,
    email: 'broker@labormobility.com',
    password: 'broker123',
    firstName: 'Maria',
    lastName: 'Martinez',
    role: 'broker',
    isActive: true,
    avatar:
      'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=150&h=150&fit=crop&crop=face',
    phone: '+1-555-0105',
    company: 'International Placement Services',
    territory: 'Latin America',
    joinedDate: '2023-08-20T00:00:00Z',
    lastLogin: '2024-01-21T11:00:00Z',
    totalReferrals: 89,
    successfulPlacements: 67,
  },
  {
    id: 6,
    email: 'employer@labormobility.com',
    password: 'employer123',
    firstName: 'Robert',
    lastName: 'Williams',
    role: 'employer',
    isActive: true,
    avatar:
      'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop&crop=face',
    phone: '+1-555-0106',
    company: 'TechCorp Solutions',
    industry: 'Technology',
    location: 'San Francisco, CA',
    joinedDate: '2023-09-10T00:00:00Z',
    lastLogin: '2024-01-21T08:45:00Z',
    activeJobs: 8,
  },
];

export const demoCandidates = [
  {
    id: 1,
    name: 'Sarah Johnson',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.johnson@email.com',
    phone: '+1-555-1001',
    nationality: 'American',
    dateOfBirth: '1995-03-15',
    status: 'Training',
    stage: 'Course Completion',
    progress: 67,
    avatar:
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    currentProgram: 'Healthcare Assistant Training',
    startDate: '2024-01-15T00:00:00Z',
    expectedCompletion: '2024-04-15T00:00:00Z',
    trainer: 'Dr. Emily Davis',
    attendanceRate: 94,
    assessmentScore: 87,
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-01-20T00:00:00Z',
    address: {
      street: '123 Main St',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90210',
      country: 'USA',
    },
    documents: [
      {
        id: 1,
        name: 'Passport.pdf',
        type: 'passport',
        status: 'verified',
        uploadedAt: '2024-01-16T00:00:00Z',
      },
      {
        id: 2,
        name: 'CV.pdf',
        type: 'cv',
        status: 'verified',
        uploadedAt: '2024-01-17T00:00:00Z',
      },
      {
        id: 3,
        name: 'Medical_Certificate.pdf',
        type: 'medical',
        status: 'pending',
        uploadedAt: '2024-01-18T00:00:00Z',
      },
    ],
    certificates: [
      {
        id: 1,
        name: 'CPR Certification',
        issueDate: '2024-01-20T00:00:00Z',
        status: 'issued',
      },
    ],
    placements: [],
  },
  {
    id: 2,
    name: 'Michael Brown',
    firstName: 'Michael',
    lastName: 'Brown',
    email: 'michael.brown@email.com',
    phone: '+1-555-1002',
    nationality: 'British',
    dateOfBirth: '1992-07-22',
    status: 'Vetting',
    stage: 'Medical Check',
    progress: 45,
    avatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    currentProgram: 'Construction Skills Training',
    startDate: '2024-01-10T00:00:00Z',
    expectedCompletion: '2024-03-10T00:00:00Z',
    trainer: 'Michael Chen',
    attendanceRate: 89,
    assessmentScore: 75,
    createdAt: '2024-01-14T00:00:00Z',
    updatedAt: '2024-01-19T00:00:00Z',
    address: {
      street: '456 Oak Ave',
      city: 'Manchester',
      state: 'England',
      zipCode: 'M1 1AA',
      country: 'UK',
    },
    documents: [
      {
        id: 4,
        name: 'Passport.pdf',
        type: 'passport',
        status: 'verified',
        uploadedAt: '2024-01-15T00:00:00Z',
      },
      {
        id: 5,
        name: 'Medical_Report.pdf',
        type: 'medical',
        status: 'under_review',
        uploadedAt: '2024-01-18T00:00:00Z',
      },
      {
        id: 6,
        name: 'Work_Permit.pdf',
        type: 'work_permit',
        status: 'pending',
        uploadedAt: '2024-01-19T00:00:00Z',
      },
    ],
    certificates: [],
    placements: [],
  },
  {
    id: 3,
    name: 'Emma Wilson',
    firstName: 'Emma',
    lastName: 'Wilson',
    email: 'emma.wilson@email.com',
    phone: '+1-555-1003',
    nationality: 'Canadian',
    dateOfBirth: '1988-11-05',
    status: 'Placed',
    stage: 'Employment',
    progress: 100,
    avatar:
      'https://images.unsplash.com/photo-1494790108755-2616b612b1e5?w=150&h=150&fit=crop&crop=face',
    currentProgram: 'Hotel Management',
    completedDate: '2024-01-05T00:00:00Z',
    trainer: 'Lisa Rodriguez',
    attendanceRate: 98,
    assessmentScore: 93,
    createdAt: '2024-01-13T00:00:00Z',
    updatedAt: '2024-01-21T00:00:00Z',
    address: {
      street: '789 Maple Dr',
      city: 'Toronto',
      state: 'ON',
      zipCode: 'M5V 3A8',
      country: 'Canada',
    },
    documents: [
      {
        id: 7,
        name: 'Passport.pdf',
        type: 'passport',
        status: 'verified',
        uploadedAt: '2024-01-14T00:00:00Z',
      },
      {
        id: 8,
        name: 'Visa.pdf',
        type: 'visa',
        status: 'verified',
        uploadedAt: '2024-01-20T00:00:00Z',
      },
      {
        id: 9,
        name: 'Employment_Contract.pdf',
        type: 'contract',
        status: 'signed',
        uploadedAt: '2024-01-21T00:00:00Z',
      },
    ],
    certificates: [
      {
        id: 2,
        name: 'Hotel Management Certificate',
        issueDate: '2024-01-05T00:00:00Z',
        status: 'issued',
      },
    ],
    placements: [
      {
        id: 1,
        employer: 'Grand Hotel International',
        position: 'Front Desk Manager',
        startDate: '2024-02-01T00:00:00Z',
        salary: 65000,
        location: 'New York, NY',
      },
    ],
  },
  {
    id: 4,
    name: 'James Rodriguez',
    firstName: 'James',
    lastName: 'Rodriguez',
    email: 'james.rodriguez@email.com',
    phone: '+1-555-1004',
    nationality: 'Mexican',
    dateOfBirth: '1990-04-18',
    status: 'Interview',
    stage: 'Employer Interview',
    progress: 85,
    avatar:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    currentProgram: 'Software Development',
    completedDate: '2024-01-08T00:00:00Z',
    trainer: 'Alex Kim',
    attendanceRate: 96,
    assessmentScore: 91,
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-01-20T00:00:00Z',
    address: {
      street: '321 Pine St',
      city: 'Mexico City',
      state: 'CDMX',
      zipCode: '01000',
      country: 'Mexico',
    },
    documents: [
      {
        id: 10,
        name: 'Passport.pdf',
        type: 'passport',
        status: 'verified',
        uploadedAt: '2024-01-11T00:00:00Z',
      },
      {
        id: 11,
        name: 'Portfolio.pdf',
        type: 'portfolio',
        status: 'verified',
        uploadedAt: '2024-01-15T00:00:00Z',
      },
    ],
    certificates: [
      {
        id: 3,
        name: 'Full Stack Development Certificate',
        issueDate: '2024-01-08T00:00:00Z',
        status: 'issued',
      },
    ],
    interviews: [
      {
        id: 1,
        employer: 'TechCorp Solutions',
        position: 'Junior Developer',
        scheduledDate: '2024-01-25T14:00:00Z',
        status: 'scheduled',
      },
    ],
  },
  {
    id: 5,
    name: 'Amara Okafor',
    firstName: 'Amara',
    lastName: 'Okafor',
    email: 'amara.okafor@email.com',
    phone: '+234-803-1234567',
    nationality: 'Nigerian',
    dateOfBirth: '1993-09-12',
    status: 'Training',
    stage: 'Practical Assessment',
    progress: 78,
    avatar:
      'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&h=150&fit=crop&crop=face',
    currentProgram: 'Nursing Assistant',
    startDate: '2024-01-05T00:00:00Z',
    expectedCompletion: '2024-04-05T00:00:00Z',
    trainer: 'Patricia Williams',
    attendanceRate: 92,
    assessmentScore: 84,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-19T00:00:00Z',
    address: {
      street: '15 Victoria Island',
      city: 'Lagos',
      state: 'Lagos',
      zipCode: '101001',
      country: 'Nigeria',
    },
    documents: [
      {
        id: 12,
        name: 'Passport.pdf',
        type: 'passport',
        status: 'verified',
        uploadedAt: '2024-01-06T00:00:00Z',
      },
      {
        id: 13,
        name: 'Nursing_Degree.pdf',
        type: 'education',
        status: 'verified',
        uploadedAt: '2024-01-07T00:00:00Z',
      },
    ],
    certificates: [],
    placements: [],
  },
];

export const demoCourses = [
  {
    id: 1,
    name: 'Healthcare Assistant Training',
    code: 'HAT-2024-01',
    description:
      'Comprehensive training program for healthcare assistants including patient care, medical terminology, and safety protocols',
    category: 'Healthcare',
    duration: 12,
    durationUnit: 'weeks',
    status: 'Active',
    enrolledStudents: 28,
    maxStudents: 30,
    completedStudents: 15,
    startDate: '2024-01-15T00:00:00Z',
    endDate: '2024-04-15T00:00:00Z',
    trainer: {
      id: 2,
      name: 'Dr. Emily Davis',
      specialization: 'Healthcare Education',
      avatar:
        'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&h=150&fit=crop&crop=face',
    },
    modules: [
      {
        id: 1,
        name: 'Introduction to Healthcare',
        duration: 40,
        status: 'completed',
      },
      {
        id: 2,
        name: 'Patient Care Fundamentals',
        duration: 50,
        status: 'active',
      },
      {
        id: 3,
        name: 'Medical Safety Protocols',
        duration: 45,
        status: 'upcoming',
      },
      { id: 4, name: 'Communication Skills', duration: 35, status: 'upcoming' },
    ],
    requirements: [
      'High School Diploma',
      'Basic English Proficiency',
      'Medical Clearance',
    ],
    certificationPath: 'Certified Healthcare Assistant (CHA)',
    placementRate: 94,
  },
  {
    id: 2,
    name: 'Construction Skills Training',
    code: 'CST-2024-01',
    description:
      'Hands-on construction training covering safety, tools, materials, and building techniques',
    category: 'Construction',
    duration: 8,
    durationUnit: 'weeks',
    status: 'Active',
    enrolledStudents: 22,
    maxStudents: 25,
    completedStudents: 8,
    startDate: '2024-01-22T00:00:00Z',
    endDate: '2024-03-22T00:00:00Z',
    trainer: {
      id: 3,
      name: 'Michael Chen',
      specialization: 'Construction Safety',
      avatar:
        'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    },
    modules: [
      {
        id: 5,
        name: 'Construction Safety & OSHA',
        duration: 30,
        status: 'active',
      },
      { id: 6, name: 'Tools and Equipment', duration: 35, status: 'upcoming' },
      { id: 7, name: 'Building Materials', duration: 25, status: 'upcoming' },
      {
        id: 8,
        name: 'Practical Construction',
        duration: 40,
        status: 'upcoming',
      },
    ],
    requirements: ['Physical Fitness', 'Basic Math Skills', 'Safety Training'],
    certificationPath: 'Certified Construction Worker (CCW)',
    placementRate: 89,
  },
  {
    id: 3,
    name: 'Hotel Management',
    code: 'HM-2024-01',
    description:
      'Comprehensive hospitality management training including operations, customer service, and leadership',
    category: 'Hospitality',
    duration: 10,
    durationUnit: 'weeks',
    status: 'Completed',
    enrolledStudents: 20,
    maxStudents: 20,
    completedStudents: 18,
    startDate: '2023-11-01T00:00:00Z',
    endDate: '2024-01-10T00:00:00Z',
    trainer: {
      id: 4,
      name: 'Lisa Rodriguez',
      specialization: 'Hospitality Management',
      avatar:
        'https://images.unsplash.com/photo-1494790108755-2616b612b1e5?w=150&h=150&fit=crop&crop=face',
    },
    modules: [
      { id: 9, name: 'Hotel Operations', duration: 40, status: 'completed' },
      {
        id: 10,
        name: 'Customer Service Excellence',
        duration: 35,
        status: 'completed',
      },
      { id: 11, name: 'Revenue Management', duration: 30, status: 'completed' },
      {
        id: 12,
        name: 'Leadership in Hospitality',
        duration: 35,
        status: 'completed',
      },
    ],
    requirements: [
      'Customer Service Experience',
      'English Fluency',
      'Professional References',
    ],
    certificationPath: 'Certified Hotel Manager (CHM)',
    placementRate: 96,
  },
  {
    id: 4,
    name: 'Software Development Bootcamp',
    code: 'SDB-2024-01',
    description:
      'Intensive full-stack web development training covering modern technologies and frameworks',
    category: 'Technology',
    duration: 16,
    durationUnit: 'weeks',
    status: 'Active',
    enrolledStudents: 15,
    maxStudents: 20,
    completedStudents: 3,
    startDate: '2024-01-08T00:00:00Z',
    endDate: '2024-04-30T00:00:00Z',
    trainer: {
      id: 5,
      name: 'Alex Kim',
      specialization: 'Full Stack Development',
      avatar:
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    },
    modules: [
      {
        id: 13,
        name: 'HTML/CSS/JavaScript',
        duration: 60,
        status: 'completed',
      },
      { id: 14, name: 'React.js Development', duration: 50, status: 'active' },
      { id: 15, name: 'Node.js & Express', duration: 45, status: 'upcoming' },
      { id: 16, name: 'Database Design', duration: 40, status: 'upcoming' },
      { id: 17, name: 'Project Development', duration: 65, status: 'upcoming' },
    ],
    requirements: [
      'Basic Computer Skills',
      'Problem-solving Aptitude',
      'English Proficiency',
    ],
    certificationPath: 'Full Stack Developer Certificate',
    placementRate: 87,
  },
];

export const demoEmployers = [
  {
    id: 1,
    name: 'TechCorp Solutions',
    industry: 'Technology',
    location: 'San Francisco, CA',
    contactPerson: 'Robert Williams',
    email: 'robert.williams@techcorp.com',
    phone: '+1-555-2001',
    website: 'https://techcorp.com',
    logo: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=150&h=150&fit=crop',
    activeJobs: 8,
    totalPlacements: 45,
    avgSalary: 85000,
    partnerSince: '2023-03-01T00:00:00Z',
    description:
      'Leading technology company specializing in software solutions',
    size: '500-1000',
    benefits: [
      'Health Insurance',
      '401k Matching',
      'Remote Work Options',
      'Professional Development',
    ],
  },
  {
    id: 2,
    name: 'Grand Hotel International',
    industry: 'Hospitality',
    location: 'New York, NY',
    contactPerson: 'Amanda Chen',
    email: 'amanda.chen@grandhotel.com',
    phone: '+1-555-2002',
    website: 'https://grandhotel.com',
    logo: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=150&h=150&fit=crop',
    activeJobs: 12,
    totalPlacements: 67,
    avgSalary: 52000,
    partnerSince: '2023-01-15T00:00:00Z',
    description: 'Luxury hotel chain with properties worldwide',
    size: '1000-5000',
    benefits: [
      'Health Insurance',
      'Employee Discounts',
      'Career Advancement',
      'Training Programs',
    ],
  },
  {
    id: 3,
    name: 'Metro Healthcare Network',
    industry: 'Healthcare',
    location: 'Chicago, IL',
    contactPerson: 'Dr. Sarah Martinez',
    email: 'sarah.martinez@metrohealthcare.com',
    phone: '+1-555-2003',
    website: 'https://metrohealthcare.com',
    logo: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=150&h=150&fit=crop',
    activeJobs: 15,
    totalPlacements: 89,
    avgSalary: 58000,
    partnerSince: '2022-11-20T00:00:00Z',
    description: 'Regional healthcare provider with multiple facilities',
    size: '2000-5000',
    benefits: [
      'Comprehensive Health Insurance',
      'Retirement Plans',
      'Continuing Education',
      'Flexible Scheduling',
    ],
  },
];

export const demoJobPostings = [
  {
    id: 1,
    title: 'Junior Software Developer',
    company: 'TechCorp Solutions',
    employerId: 1,
    location: 'San Francisco, CA',
    type: 'Full-time',
    remote: true,
    salary: { min: 75000, max: 95000, currency: 'USD' },
    description:
      'Join our dynamic development team to build cutting-edge software solutions',
    requirements: [
      'React.js experience',
      'JavaScript proficiency',
      'Problem-solving skills',
    ],
    benefits: [
      'Health Insurance',
      '401k Matching',
      'Remote Work',
      'Professional Development',
    ],
    postedDate: '2024-01-15T00:00:00Z',
    applicationDeadline: '2024-02-15T00:00:00Z',
    status: 'Active',
    applicants: 23,
    category: 'Technology',
  },
  {
    id: 2,
    title: 'Front Desk Manager',
    company: 'Grand Hotel International',
    employerId: 2,
    location: 'New York, NY',
    type: 'Full-time',
    remote: false,
    salary: { min: 55000, max: 70000, currency: 'USD' },
    description:
      'Lead our front desk operations and provide exceptional guest service',
    requirements: [
      'Hotel management experience',
      'Customer service skills',
      'Leadership abilities',
    ],
    benefits: ['Health Insurance', 'Employee Discounts', 'Career Growth'],
    postedDate: '2024-01-10T00:00:00Z',
    applicationDeadline: '2024-02-10T00:00:00Z',
    status: 'Active',
    applicants: 18,
    category: 'Hospitality',
  },
  {
    id: 3,
    title: 'Healthcare Assistant',
    company: 'Metro Healthcare Network',
    employerId: 3,
    location: 'Chicago, IL',
    type: 'Full-time',
    remote: false,
    salary: { min: 45000, max: 60000, currency: 'USD' },
    description: 'Support medical staff in providing quality patient care',
    requirements: [
      'Healthcare certification',
      'Patient care experience',
      'Medical knowledge',
    ],
    benefits: ['Health Insurance', 'Retirement Plan', 'Continuing Education'],
    postedDate: '2024-01-12T00:00:00Z',
    applicationDeadline: '2024-02-12T00:00:00Z',
    status: 'Active',
    applicants: 31,
    category: 'Healthcare',
  },
];

export const demoDashboardStats = {
  totalCandidates: 1847,
  activeCandidates: 1234,
  placedCandidates: 567,
  activeCourses: 28,
  completedCourses: 156,
  totalTrainers: 45,
  placementRate: 82.3,
  revenue: 2450000,
  monthlyGrowth: 15.7,
  completionRate: 89.4,
  averageSalary: 67500,
  partnerEmployers: 89,
  activeJobs: 156,
  totalPlacements: 2341,
};

export const demoPlacementsOverTime = [
  { month: 'Jul 2023', placements: 42, revenue: 126000, candidates: 156 },
  { month: 'Aug 2023', placements: 38, revenue: 114000, candidates: 178 },
  { month: 'Sep 2023', placements: 51, revenue: 153000, candidates: 189 },
  { month: 'Oct 2023', placements: 47, revenue: 141000, candidates: 201 },
  { month: 'Nov 2023', placements: 55, revenue: 165000, candidates: 223 },
  { month: 'Dec 2023', placements: 49, revenue: 147000, candidates: 234 },
  { month: 'Jan 2024', placements: 67, revenue: 201000, candidates: 267 },
];

export const demoCandidatesByStatus = [
  { name: 'Training', value: 45, color: '#3B82F6', percentage: 37.5 },
  { name: 'Vetting', value: 23, color: '#F59E0B', percentage: 19.2 },
  { name: 'Interview', value: 18, color: '#8B5CF6', percentage: 15.0 },
  { name: 'Placed', value: 34, color: '#10B981', percentage: 28.3 },
];

export const demoCandidatesByProgram = [
  { name: 'Healthcare', value: 567, color: '#EF4444' },
  { name: 'Technology', value: 423, color: '#3B82F6' },
  { name: 'Hospitality', value: 312, color: '#F59E0B' },
  { name: 'Construction', value: 289, color: '#8B5CF6' },
  { name: 'Manufacturing', value: 234, color: '#10B981' },
];

export const demoRevenueByMonth = [
  { month: 'Jan', revenue: 185000, placements: 62 },
  { month: 'Feb', revenue: 201000, placements: 67 },
  { month: 'Mar', revenue: 178000, placements: 59 },
  { month: 'Apr', revenue: 223000, placements: 74 },
  { month: 'May', revenue: 198000, placements: 66 },
  { month: 'Jun', revenue: 245000, placements: 82 },
];

export const demoNotifications = [
  {
    id: 1,
    title: 'New Candidate Registration',
    message:
      'Sarah Johnson has completed the Healthcare Assistant program registration',
    type: 'info',
    read: false,
    priority: 'medium',
    actionRequired: false,
    createdAt: '2024-01-21T10:30:00Z',
    category: 'registration',
  },
  {
    id: 2,
    title: 'Course Completion Alert',
    message:
      'Hotel Management course has been completed by 18 out of 20 students',
    type: 'success',
    read: false,
    priority: 'low',
    actionRequired: false,
    createdAt: '2024-01-21T09:15:00Z',
    category: 'course',
  },
  {
    id: 3,
    title: 'Document Verification Needed',
    message: 'Michael Brown requires medical certificate verification',
    type: 'warning',
    read: false,
    priority: 'high',
    actionRequired: true,
    createdAt: '2024-01-21T08:45:00Z',
    category: 'document',
  },
  {
    id: 4,
    title: 'Placement Opportunity',
    message:
      'New job opening matching James Rodriguez profile at TechCorp Solutions',
    type: 'info',
    read: false,
    priority: 'high',
    actionRequired: true,
    createdAt: '2024-01-21T07:30:00Z',
    category: 'placement',
  },
  {
    id: 5,
    title: 'Interview Scheduled',
    message:
      'Interview scheduled for James Rodriguez on Jan 25, 2024 at 2:00 PM',
    type: 'info',
    read: true,
    priority: 'medium',
    actionRequired: false,
    createdAt: '2024-01-20T16:20:00Z',
    category: 'interview',
  },
];

export const demoRecentActivity = [
  {
    id: 1,
    action: 'Candidate Registered',
    user: 'Sarah Johnson',
    userType: 'candidate',
    description: 'Registered for Healthcare Assistant Training program',
    timestamp: '2024-01-21T10:30:00Z',
    type: 'registration',
    priority: 'low',
  },
  {
    id: 2,
    action: 'Document Uploaded',
    user: 'Michael Brown',
    userType: 'candidate',
    description: 'Uploaded medical certificate for verification',
    timestamp: '2024-01-21T09:15:00Z',
    type: 'document',
    priority: 'medium',
  },
  {
    id: 3,
    action: 'Course Completed',
    user: 'Emma Wilson',
    userType: 'candidate',
    description: 'Successfully completed Hotel Management program',
    timestamp: '2024-01-21T08:45:00Z',
    type: 'completion',
    priority: 'high',
  },
  {
    id: 4,
    action: 'Interview Scheduled',
    user: 'James Rodriguez',
    userType: 'candidate',
    description: 'Interview scheduled with TechCorp Solutions',
    timestamp: '2024-01-21T07:30:00Z',
    type: 'interview',
    priority: 'medium',
  },
  {
    id: 5,
    action: 'Assessment Graded',
    user: 'Michael Chen',
    userType: 'trainer',
    description: 'Graded 15 practical assessments for Construction Skills',
    timestamp: '2024-01-20T16:45:00Z',
    type: 'assessment',
    priority: 'low',
  },
];

export const demoAttendanceData = [
  {
    id: 1,
    candidateId: 1,
    candidateName: 'Sarah Johnson',
    courseId: 1,
    courseName: 'Healthcare Assistant Training',
    date: '2024-01-21',
    status: 'present',
    checkInTime: '08:00',
    checkOutTime: '17:00',
    hoursAttended: 8,
  },
  {
    id: 2,
    candidateId: 2,
    candidateName: 'Michael Brown',
    courseId: 2,
    courseName: 'Construction Skills Training',
    date: '2024-01-21',
    status: 'present',
    checkInTime: '08:15',
    checkOutTime: '17:00',
    hoursAttended: 7.75,
  },
  {
    id: 3,
    candidateId: 5,
    candidateName: 'Amara Okafor',
    courseId: 1,
    courseName: 'Healthcare Assistant Training',
    date: '2024-01-21',
    status: 'late',
    checkInTime: '08:30',
    checkOutTime: '17:00',
    hoursAttended: 7.5,
  },
];

export const demoAssessmentResults = [
  {
    id: 1,
    candidateId: 1,
    candidateName: 'Sarah Johnson',
    courseId: 1,
    courseName: 'Healthcare Assistant Training',
    moduleId: 1,
    moduleName: 'Introduction to Healthcare',
    assessmentType: 'quiz',
    score: 87,
    maxScore: 100,
    passed: true,
    completedDate: '2024-01-20T00:00:00Z',
    feedback: 'Excellent understanding of healthcare fundamentals',
  },
  {
    id: 2,
    candidateId: 2,
    candidateName: 'Michael Brown',
    courseId: 2,
    courseName: 'Construction Skills Training',
    moduleId: 5,
    moduleName: 'Construction Safety & OSHA',
    assessmentType: 'practical',
    score: 75,
    maxScore: 100,
    passed: true,
    completedDate: '2024-01-19T00:00:00Z',
    feedback: 'Good safety practices, needs improvement in equipment handling',
  },
];

// Mock API responses
export const mockApiResponses = {
  login: credentials => {
    const user = demoUsers.find(u => u.email === credentials.email);
    if (user && user.password === credentials.password) {
      return {
        user: {
          id: user.id,
          email: user.email,
          firstName: user.firstName,
          lastName: user.lastName,
          role: user.role,
          avatar: user.avatar,
          phone: user.phone,
          department: user.department,
        },
        accessToken: `mock-access-token-${user.id}`,
        refreshToken: `mock-refresh-token-${user.id}`,
      };
    }
    throw new Error('Invalid credentials');
  },

  getDashboard: userRole => ({
    stats: demoDashboardStats,
    placementsOverTime: demoPlacementsOverTime,
    candidatesByStatus: demoCandidatesByStatus,
    candidatesByProgram: demoCandidatesByProgram,
    revenueByMonth: demoRevenueByMonth,
    recentCandidates: demoCandidates.slice(0, 5),
    recentActivity: demoRecentActivity.slice(0, 5),
    notifications: demoNotifications.filter(n => !n.read).slice(0, 3),
  }),

  getCandidates: (params = {}) => ({
    candidates: demoCandidates,
    pagination: {
      page: params.page || 1,
      limit: params.limit || 10,
      total: demoCandidates.length,
    },
  }),

  getCourses: (params = {}) => ({
    courses: demoCourses,
    pagination: {
      page: params.page || 1,
      limit: params.limit || 10,
      total: demoCourses.length,
    },
  }),

  getEmployers: (params = {}) => ({
    employers: demoEmployers,
    pagination: {
      page: params.page || 1,
      limit: params.limit || 10,
      total: demoEmployers.length,
    },
  }),

  getJobPostings: (params = {}) => ({
    jobs: demoJobPostings,
    pagination: {
      page: params.page || 1,
      limit: params.limit || 10,
      total: demoJobPostings.length,
    },
  }),

  getNotifications: userId => ({
    notifications: demoNotifications,
    unreadCount: demoNotifications.filter(n => !n.read).length,
  }),

  getAttendance: (params = {}) => ({
    attendance: demoAttendanceData,
    summary: {
      totalSessions: 120,
      presentSessions: 108,
      lateSessions: 8,
      absentSessions: 4,
      attendanceRate: 90,
    },
  }),

  getAssessments: (params = {}) => ({
    assessments: demoAssessmentResults,
    summary: {
      totalAssessments: 25,
      passed: 23,
      failed: 2,
      averageScore: 82.3,
      passRate: 92,
    },
  }),
};
